In [1]:
import pandas as pd
import numpy as np

In [2]:
sales_data = {
   'Transaction_id' : [101,102,103,104,105,106,107,108,109,110],
    'Cust_id' : [501,502,503,504,505,506,507,508,509,510],
    'Product_category' : ['Electronics','Clothing','Electronics','Home','Clothing','Home','Electronics','Books','Clothing','Books'],
    'Quantity_ordered' : [2,1,np.nan,3,1,2,2,5,1,np.nan],
    'Price_per_unit_INR' : [15000,1200,25000,4500,1200,3000,15000,600,30000,80000]
    }

In [3]:
customer_data = {
     'Cust_id' : [501,502,503,504,505,506,507,508,509,510],
    'Customer_Name' : ['Bhagyashri', 'Amit', 'Rahul', 'Priya', 'Sanjay', 'Deepak', 'Neha','Shiv','Ragini','Viraj'],
    'City': ['Pune', 'Mumbai', 'Pune', 'Delhi', 'Mumbai', 'Bangalore', 'Chennai','Karnataka','Delhi','Surat']
}

In [4]:
df_sales = pd.DataFrame(sales_data)
df_customer = pd.DataFrame(customer_data)

In [5]:
print("Sales DataFrame Loaded:")
print(df_sales.head(5))
print("\ncustomer DataFrame Loaded:")
print(df_customer.head(5))

Sales DataFrame Loaded:
   Transaction_id  Cust_id Product_category  Quantity_ordered  \
0             101      501      Electronics               2.0
1             102      502         Clothing               1.0
2             103      503      Electronics               NaN
3             104      504             Home               3.0
4             105      505         Clothing               1.0

   Price_per_unit_INR
0               15000
1                1200
2               25000
3                4500
4                1200

customer DataFrame Loaded:
   Cust_id Customer_Name    City
0      501    Bhagyashri    Pune
1      502          Amit  Mumbai
2      503         Rahul    Pune
3      504         Priya   Delhi
4      505        Sanjay  Mumbai

In [6]:
# 1. Checking for missing (NaN) values in the Sales DataFrame

In [7]:
print(df_sales.isnull().sum())

Transaction_id        0
Cust_id               0
Product_category      0
Quantity_ordered      2
Price_per_unit_INR    0
dtype: int64

In [8]:
# 2. Filling the missing values in 'Quantity_ordered' with a default value of 1
# SQL Equivalent: COALESCE(Quantity_ordered, 1)

In [9]:
df_sales['Quantity_ordered'] = df_sales['Quantity_ordered'].fillna(1)

In [10]:
# 3. Checking the data after filling missing values
print(df_sales.isnull().sum())

Transaction_id        0
Cust_id               0
Product_category      0
Quantity_ordered      0
Price_per_unit_INR    0
dtype: int64

In [11]:
# 4. Finding and removing duplicate transactions (If any)
# SQL Equivalent: SELECT DISTINCT *

In [12]:
(len(df_sales))

10

In [13]:
df_sales= df_sales.drop_duplicates()

In [14]:
(len(df_sales))

10

In [15]:
# 1. Renaming column names to make them look cleaner
# SQL Equivalent: SELECT Cust_id AS Customer_ID, Price_per_unit_INR AS Price_INR

In [16]:
df_sales = df_sales.rename(columns={
    'Cust_id': 'Customer_id',
    'Price_per_unit_INR' : 'Price_INR'})

In [17]:
df_sales

   Transaction_id  Customer_id Product_category  Quantity_ordered  Price_INR
0             101          501      Electronics               2.0      15000
1             102          502         Clothing               1.0       1200
2             103          503      Electronics               1.0      25000
3             104          504             Home               3.0       4500
4             105          505         Clothing               1.0       1200
5             106          506             Home               2.0       3000
6             107          507      Electronics               2.0      15000
7             108          508            Books               5.0        600
8             109          509         Clothing               1.0      30000
9             110          510            Books               1.0      80000

In [18]:
df_sales['Quantity_ordered'] = df_sales['Quantity_ordered'].astype(int)

In [19]:
(df_sales.dtypes)

Transaction_id       int64
Customer_id          int64
Product_category    object
Quantity_ordered     int64
Price_INR            int64
dtype: object

In [20]:
# Using loc for Multiple Conditions (SQL: WHERE Product_category = 'Electronics' AND Price_INR > 10000)

In [22]:
advanced_filter = df_sales.loc[(df_sales['Product_category'] == 'Electronics') & (df_sales['Price_INR'] > 10000)]

In [23]:
advanced_filter

   Transaction_id  Customer_id Product_category  Quantity_ordered  Price_INR
0             101          501      Electronics                 2      15000
2             103          503      Electronics                 1      25000
6             107          507      Electronics                 2      15000

In [24]:
# SQL Equivalent: SELECT Product_category, SUM(Quantity_ordered), SUM(Price_INR) FROM df_sales GROUP BY Product_category

In [26]:
grouping = df_sales.groupby('Product_category').agg (Total_Quantity = ('Quantity_ordered','sum'), Total_Revenue= ('Price_INR','sum')).reset_index()

In [27]:
grouping

  Product_category  Total_Quantity  Total_Revenue
0            Books               6          80600
1         Clothing               3          32400
2      Electronics               5          55000
3             Home               5           7500

In [28]:
# SQL Equivalent: SELECT * FROM df_sales s INNER JOIN df_customer c ON s.Customer_id = c.Cust_id
# Note: df_customer contains 'Cust_id', so we use left_on and right_on

In [30]:
merge_on = pd.merge(df_sales,df_customer, left_on= 'Customer_id', right_on= 'Cust_id',how = 'inner')

In [31]:
merge_on

,Transaction_id,Customer_id,Product_category,Quantity_ordered,Price_INR,Cust_id,Customer_Name,City
0,101,501,Electronics,2,15000,501,Bhagyashri,Pune
1,102,502,Clothing,1,1200,502,Amit,Mumbai
2,103,503,Electronics,1,25000,503,Rahul,Pune
3,104,504,Home,3,4500,504,Priya,Delhi
4,105,505,Clothing,1,1200,505,Sanjay,Mumbai
5,106,506,Home,2,3000,506,Deepak,Bangalore
6,107,507,Electronics,2,15000,507,Neha,Chennai
7,108,508,Books,5,600,508,Shiv,Karnataka
8,109,509,Clothing,1,30000,509,Ragini,Delhi
9,110,510,Books,1,80000,510,Viraj,Surat

In [32]:
new_row = pd.DataFrame([{'Transaction_id': 111,
                         'Customer_id' : 999,
                         'Product_category' : 'Books',
                         'Quantity_ordered' : 1,
                         'Price_INR' : 500
                        }])
df_sales_new = pd.concat([df_sales,new_row], ignore_index = True)

In [35]:
left_merge = pd.merge(df_sales_new,df_customer,left_on = 'Customer_id', right_on ='Cust_id',how = 'left')

In [36]:
left_merge

,Transaction_id,Customer_id,Product_category,Quantity_ordered,Price_INR,Cust_id,Customer_Name,City
0,101,501,Electronics,2,15000,501.0,Bhagyashri,Pune
1,102,502,Clothing,1,1200,502.0,Amit,Mumbai
2,103,503,Electronics,1,25000,503.0,Rahul,Pune
3,104,504,Home,3,4500,504.0,Priya,Delhi
4,105,505,Clothing,1,1200,505.0,Sanjay,Mumbai
5,106,506,Home,2,3000,506.0,Deepak,Bangalore
6,107,507,Electronics,2,15000,507.0,Neha,Chennai
7,108,508,Books,5,600,508.0,Shiv,Karnataka
8,109,509,Clothing,1,30000,509.0,Ragini,Delhi
9,110,510,Books,1,80000,510.0,Viraj,Surat
10,111,999,Books,1,500,NaN,NaN,NaN

In [37]:
# 1.Creating a new secondary sales dataframe

In [43]:
additional_sales = pd.DataFrame({
                        'Transaction_id': [112,113],
                         'Customer_id' : [501,502],
                         'Product_category' : ['Home','Books'],
                         'Quantity_ordered' : [1,2],
                         'Price_INR' : [2500,1200]
                        })

In [44]:
additional_sales

   Transaction_id  Customer_id Product_category  Quantity_ordered  Price_INR
0             112          501             Home                 1       2500
1             113          502            Books                 2       1200

In [48]:
final = pd.concat([df_sales, additional_sales], ignore_index = True)

In [49]:
final

    Transaction_id  Customer_id Product_category  Quantity_ordered  Price_INR
0              101          501      Electronics                 2      15000
1              102          502         Clothing                 1       1200
2              103          503      Electronics                 1      25000
3              104          504             Home                 3       4500
4              105          505         Clothing                 1       1200
5              106          506             Home                 2       3000
6              107          507      Electronics                 2      15000
7              108          508            Books                 5        600
8              109          509         Clothing                 1      30000
9              110          510            Books                 1      80000
10             112          501             Home                 1       2500
11             113          502            Books                 2       1200

In [59]:
last_merge = pd.merge( final,df_customer,left_on = 'Customer_id', right_on = 'Cust_id', how = 'left')

In [60]:
last_merge

,Transaction_id,Customer_id,Product_category,Quantity_ordered,Price_INR,Cust_id,Customer_Name,City
0,101,501,Electronics,2,15000,501,Bhagyashri,Pune
1,102,502,Clothing,1,1200,502,Amit,Mumbai
2,103,503,Electronics,1,25000,503,Rahul,Pune
3,104,504,Home,3,4500,504,Priya,Delhi
4,105,505,Clothing,1,1200,505,Sanjay,Mumbai
5,106,506,Home,2,3000,506,Deepak,Bangalore
6,107,507,Electronics,2,15000,507,Neha,Chennai
7,108,508,Books,5,600,508,Shiv,Karnataka
8,109,509,Clothing,1,30000,509,Ragini,Delhi
9,110,510,Books,1,80000,510,Viraj,Surat
10,112,501,Home,1,2500,501,Bhagyashri,Pune
11,113,502,Books,2,1200,502,Amit,Mumbai

In [61]:
# 1. Sorting the sales dataframe by Price_INR in descending order (Highest Price First)
# SQL Equivalent: SELECT * FROM df_sales ORDER BY Price_INR DESC

In [64]:
sorted_sales = df_sales.sort_values(by = 'Price_INR',ascending =False)

In [65]:
sorted_sales.head(3)

   Transaction_id  Customer_id Product_category  Quantity_ordered  Price_INR
9             110          510            Books                 1      80000
8             109          509         Clothing                 1      30000
2             103          503      Electronics                 1      25000

In [66]:
# 2. Filtering rows where Product_category starts with or contains 'Elec'
# SQL Equivalent: SELECT * FROM df_sales WHERE Product_category LIKE '%Elec%'

In [69]:
filter_with_letter = df_sales[df_sales['Product_category'].str.contains('Elec',case=False)]

In [70]:
filter_with_letter

   Transaction_id  Customer_id Product_category  Quantity_ordered  Price_INR
0             101          501      Electronics                 2      15000
2             103          503      Electronics                 1      25000
6             107          507      Electronics                 2      15000